# Generated by Django 5.2.5 on 2025-09-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identity_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
